### ISSUE TITLE
Is it possible to use superscripts or subscripts with this library? If so how? If not, we'd love the feature!

### ISSUE THREAD

**Issue by Ryanauger95** [johnxnguyen/Down#257]
# Feature Request

Superscript / Subscript support, like Github's markdown, or even using inline HTML <sup></sup>

**Comment by johnxnguyen** [comment]
Hi @Ryanauger95 , thanks for getting in touch. Unfortunately superscripts and subscripts are not part of the [Commonmark specification](https://spec.commonmark.org/0.29/). 

It _may be possible_ (I haven't tried it) to use inline html, but it only when using the `DownView` which uses a web view to render the content. However, if you rely on using the `DownStyler` it certainly won't work because this flavor or the markdown rendering doesn't support html parsing.

In terms of adding support for this, it's something that needs to be done in the cmark parser, which I don't intend to do here because `Down` is only a wrapper around cmark.

I hope this answers you questions.

**Comment by Ryanauger95** [comment]
This does help - I appreciate the quick reply. I figured we could use special unicode superscript characters

**Comment by johnxnguyen** [comment]
@Ryanauger95  no problem, let me know if there's anything else I can help you with.
